# Generated by Django 4.0.5 on 2024-06-13 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_usuario_cc_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesajeSubproducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_sebo', models.FloatField(db_column='ps_peso_sebo')),
                ('peso_esofago', models.FloatField(db_column='ps_peso_esofago')),
                ('fecha', models.DateTimeField(db_column='ps_fecha')),
                ('serie', models.IntegerField(db_column='ps_serie')),
                ('responsable', models.IntegerField(db_column='ps_responsable')),
                ('usuario', models.ForeignKey(db_column='ps_fk_usuario', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='users.usuario')),
            ],
            options={
                'db_table': 'pesaje_subproducto',
            },
        ),
    ]
