# Generated by Django 4.0.5 on 2024-06-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(db_column='us_usuario', max_length=20, unique=True)),
                ('password', models.CharField(db_column='us_pass', max_length=255)),
                ('cc_documento', models.IntegerField(db_column='us_cc_documento')),
                ('nombre', models.CharField(db_column='us_nombre', max_length=50)),
                ('apellido', models.CharField(db_column='us_apellido', max_length=50)),
                ('tipo_usuario', models.CharField(db_column='us_tipo_usuario', max_length=20)),
                ('telefono', models.CharField(db_column='us_telefono', max_length=25)),
                ('direccion', models.CharField(db_column='us_direccion', max_length=255)),
                ('fecha_nacimiento', models.DateTimeField(auto_now=True, db_column='us_fecha_nacimiento')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
