# Generated by Django 4.0.5 on 2024-06-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cc_documento',
            field=models.IntegerField(db_column='us_cc_documento', unique=True),
        ),
    ]
