# Generated by Django 4.0.5 on 2024-06-13 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pesaje_subproducto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vicera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.IntegerField(db_column='vc_turno')),
                ('cifra', models.IntegerField(db_column='vc_cifra')),
                ('peso', models.IntegerField(db_column='vc_peso')),
                ('serie', models.CharField(db_column='us_serie', max_length=15)),
                ('responsable_firma', models.IntegerField(db_column='vc_responsable_firma')),
                ('tipo_vicera', models.CharField(db_column='us_tipo_vicera', max_length=150)),
                ('pesaje_subproducto', models.ForeignKey(db_column='vc_fk_pesaje_subproducto', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='pesaje_subproducto.pesajesubproducto')),
            ],
            options={
                'db_table': 'vicera',
            },
        ),
    ]
