# Generated by Django 4.0.5 on 2024-06-14 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vicera', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vicera',
            name='pesaje_subproducto',
        ),
    ]
