# Generated by Django 4.0.5 on 2024-06-13 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_usuario_cc_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decomiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(db_column='dc_ciudad', max_length=25)),
                ('producto', models.CharField(db_column='dc_producto', max_length=25)),
                ('serie', models.CharField(db_column='dc_serie', max_length=15)),
                ('fecha', models.DateTimeField(db_column='dc_fecha')),
                ('cifra', models.IntegerField(db_column='dc_cifra')),
                ('cantidad', models.IntegerField(db_column='dc_cantidad')),
                ('causa', models.CharField(db_column='dc_causa', max_length=255)),
                ('profesional_cargo', models.IntegerField(db_column='dc_profesional_cargo')),
                ('foto', models.CharField(db_column='dc_foto', max_length=150)),
                ('veterinario', models.IntegerField(db_column='dc_veterinario')),
                ('turno', models.IntegerField(db_column='dc_turno')),
                ('usuario', models.ForeignKey(db_column='dc_fk_usuario', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='users.usuario')),
            ],
            options={
                'db_table': 'decomiso',
            },
        ),
    ]
