# Generated by Django 4.0.5 on 2024-06-14 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vicera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.IntegerField(db_column='vc_turno')),
                ('cifra', models.IntegerField(db_column='vc_cifra')),
                ('peso', models.IntegerField(db_column='vc_peso')),
                ('serie', models.CharField(db_column='vc_serie', max_length=15)),
                ('responsable_firma', models.IntegerField(db_column='vc_responsable_firma')),
                ('tipo_vicera', models.CharField(db_column='vc_tipo_vicera', max_length=150)),
            ],
            options={
                'db_table': 'vicera',
            },
        ),
        migrations.CreateModel(
            name='PesajeSubproducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_sebo', models.FloatField(db_column='ps_peso_sebo')),
                ('peso_esofago', models.FloatField(db_column='ps_peso_esofago')),
                ('fecha', models.DateTimeField(auto_now=True, db_column='ps_fecha')),
                ('serie', models.IntegerField(db_column='ps_serie')),
                ('responsable', models.IntegerField(db_column='ps_responsable')),
                ('usuario', models.ForeignKey(db_column='ps_fk_usuario', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='users.usuario')),
                ('vicera', models.ForeignKey(db_column='ps_fk_vicera', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='frontera_auto_modulos.vicera')),
            ],
            options={
                'db_table': 'pesaje_subproducto',
            },
        ),
        migrations.CreateModel(
            name='Decomiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(db_column='dc_ciudad', max_length=25)),
                ('producto', models.CharField(db_column='dc_producto', max_length=25)),
                ('serie', models.CharField(db_column='dc_serie', max_length=15)),
                ('fecha', models.DateTimeField(db_column='dc_fecha')),
                ('cifra', models.IntegerField(db_column='dc_cifra')),
                ('cantidad', models.IntegerField(db_column='dc_cantidad')),
                ('causa', models.CharField(db_column='dc_causa', max_length=255)),
                ('profesional_cargo', models.IntegerField(db_column='dc_profesional_cargo')),
                ('foto', models.CharField(db_column='dc_foto', max_length=150)),
                ('veterinario', models.IntegerField(db_column='dc_veterinario')),
                ('turno', models.IntegerField(db_column='dc_turno')),
                ('usuario', models.ForeignKey(db_column='dc_fk_usuario', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='users.usuario')),
            ],
            options={
                'db_table': 'decomiso',
            },
        ),
    ]
