# Generated by Django 4.0.5 on 2024-06-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontera_auto_modulos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decomiso',
            name='profesional_cargo',
        ),
        migrations.RemoveField(
            model_name='decomiso',
            name='veterinario',
        ),
    ]
