# Generated by Django 4.0.5 on 2024-06-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontera_auto_modulos', '0003_alter_decomiso_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decomiso',
            name='foto',
            field=models.ImageField(db_column='dc_foto', upload_to='fotos/'),
        ),
    ]
