# Generated by Django 4.0.5 on 2024-06-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontera_auto_modulos', '0004_alter_decomiso_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='decomiso',
            name='observacion',
            field=models.CharField(blank=True, db_column='dc_observacion', max_length=255),
        ),
    ]
